added bench.

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -24,11 +24,34 @@ jobs:
         ruby-version: '3.2'
         bundler-cache: false
     - name: Build
+      continue-on-error: true # とにかく最後まで行きたい
       run: |
         cargo build --verbose
+    - name: Run clippy
+      continue-on-error: true # とにかく最後まで行きたい
+      id: ruclippy
+      run: cargo clippy --all-targets
     - name: Run tests
+      continue-on-error: true # とにかく最後まで行きたい
       id: utest
       run: cargo test --features=avx --verbose --release  # test w/ simd will get error w/o --release.
+    - name: check error run build
+      if: ${{ steps.rubuild.outcome == 'failure' }}
+      run: |
+        echo ${{ steps.rubuild.outcome }} == 'failure'
+        exit 1
+    - name: check error run clippy
+      if: ${{ steps.ruclippy.outcome == 'failure' }}
+      run: |
+        echo ${{ steps.ruclippy.outcome }} == 'failure'
+        exit 1
+    - name: check error run test
+      if: ${{ steps.rutest.outcome == 'failure' }}
+      run: |
+        echo ${{ steps.rutest.outcome }} == 'failure'
+        exit 1
+    - name: Run bench
+      run: cargo bench
     - name: Speed check search
       run: ruby ./tools/runspeedcheck.rb search
     - name: Speed check game
@@ -50,21 +73,40 @@ jobs:
     - uses: actions/checkout@v4
     - name: cpu
       run: cat /proc/cpuinfo
-    # - name: Set up Ruby
-    #   uses: ruby/setup-ruby@v1
-    #   with:
-    #     ruby-version: '3.2'
-    #     bundler-cache: false
+    - name: Set up Ruby
+      continue-on-error: true # とにかく最後まで行きたい
+      uses: ruby/setup-ruby@v1
+      with:
+        ruby-version: '3.2'
+        bundler-cache: false
     - name: Build
+      continue-on-error: true # とにかく最後まで行きたい
       run: |
         cargo build --verbose
     - name: Run tests
+      continue-on-error: true # とにかく最後まで行きたい
       id: utest
       run: cargo test --verbose --release
+    - name: check error run build
+      if: ${{ steps.rubuild.outcome == 'failure' }}
+      run: |
+        echo ${{ steps.rubuild.outcome }} == 'failure'
+        exit 1
+    - name: check error run test
+      if: ${{ steps.rutest.outcome == 'failure' }}
+      run: |
+        echo ${{ steps.rutest.outcome }} == 'failure'
+        exit 1
+    - name: Run bench
+      run: cargo bench
     - name: Speed check search
-      run: ./tools/runspeedcheck.sh search
+      run: ./tools/speedcheck.sh search
     - name: Speed check game
-      run: ./tools/runspeedcheck.sh game
+      run: ./tools/speedcheck.sh game
+    - name: Speed check search
+      run: ruby ./tools/runspeedcheck.rb search
+    - name: Speed check game
+      run: ruby ./tools/runspeedcheck.rb game
 
   build_mac:
     runs-on: macos-latest
@@ -97,6 +139,8 @@ jobs:
       run: |
         echo ${{ steps.rutest.outcome }} == 'failure'
         exit 1
+    - name: Run bench
+      run: cargo bench
     - name: Speed check search
       run: ruby ./tools/runspeedcheck.rb search
     - name: Speed check game
